# Create GitHub Action Secrets for your version of the application:
#   DEBRICKED_TOKEN should be the API token obtained from Debricked.
name: Fortify SCA Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master", "fortify-demo" ]
  push:
    branches: [ "master", "fortify-demo" ]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
